# Generated by Django 5.2.16 on 2026-09-05 17:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "email",
                    models.EmailField(
                        help_text="Where payout confirmations and any admin notices go.",
                        max_length=254,
                    ),
                ),
                (
                    "referral_code",
                    models.SlugField(
                        blank=True,
                        help_text="What goes in their link (codesecureacademy.com/r/<code>/). Auto-generated if left blank.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "enrollment_commission_percent",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("10.0"),
                        help_text="Percent of the cohort price paid out when someone they referred enrolls.",
                        max_digits=4,
                    ),
                ),
                (
                    "marketplace_commission_percent",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("5.0"),
                        help_text="Percent of the order amount paid out when someone they referred buys on the marketplace.",
                        max_digits=4,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Turn off to stop crediting new referrals without deleting history.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReferralAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_users",
                        to="referrals.partner",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_attribution",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferralCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("enrollment", "Cohort enrollment"),
                            ("marketplace", "Marketplace order"),
                        ],
                        max_length=12,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "source_amount_naira",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                (
                    "commission_amount_naira",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved, awaiting payout"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="referrals.partner",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id"),
                        name="unique_commission_per_source",
                    )
                ],
            },
        ),
    ]
