# Generated by Django 5.2.16 on 2026-10-09 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Their login for the partner dashboard — created automatically when this partner is added.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
