# Generated by Django 5.2.16 on 2026-08-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="highlights",
            field=models.TextField(
                blank=True,
                help_text="What students will learn/build — one point per line. Shown as a bullet list on the track page.",
            ),
        ),
    ]
