# Generated by Django 5.2.16 on 2026-08-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0002_track_highlights"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="why_join",
            field=models.TextField(
                blank=True,
                help_text="Short, punchy reasons to register for this specific track — one per line. Shown as the scroll-driven 'why register' story section on the track page.",
            ),
        ),
    ]
