# Generated by Django 5.2.16 on 2026-08-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0003_track_why_join"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="cover_image_url",
            field=models.URLField(
                blank=True,
                help_text="A hotlinked image URL (e.g. a properly-licensed Unsplash photo) — used until a real uploaded photo replaces it. Attribution isn't required by the Unsplash License but is good practice.",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Uploaded via Cloudinary. Takes priority over Cover image URL below if both are set.",
                null=True,
                upload_to="tracks/",
            ),
        ),
    ]
