# Generated by Django 5.2.16 on 2026-08-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0004_track_cover_image_url_alter_track_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="enrollment_deadline",
            field=models.DateField(
                blank=True,
                help_text="Last day new enrollments are accepted for this cohort. Leave blank for no cutoff.",
                null=True,
            ),
        ),
    ]
