# Generated by Django 5.2.16 on 2026-08-02 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cohorts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackWhatsAppGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invite_link",
                    models.URLField(
                        help_text="e.g. https://chat.whatsapp.com/XXXXXXXXXXXXXXXXXXXXXX"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_group",
                        to="cohorts.track",
                    ),
                ),
            ],
        ),
    ]
