# Generated by Django 5.2.16 on 2026-08-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_fix_default_site_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-joined_at"],
            },
        ),
    ]
