# Generated by Django 5.2.16 on 2026-09-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_waitlistsignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="last_deadline_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the enrollment-deadline reminder email was last blasted out. Set automatically — the reminder re-sends itself every few days until the deadline passes.",
                null=True,
            ),
        ),
    ]
