# Generated by Django 5.2.16 on 2026-09-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_sitesettings_last_deadline_reminder_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOptOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="last_deadline_reminder_variant",
            field=models.SmallIntegerField(
                default=-1,
                help_text="Index of the last reminder variant sent, so the next automatic send rotates to a different one instead of repeating the same email every time.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="last_deadline_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the enrollment-reminder campaign last sent an email. Set automatically — the campaign re-sends itself on its own schedule until the deadline passes.",
                null=True,
            ),
        ),
    ]
