# Generated by Django 5.2.16 on 2026-09-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_emailoptout_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderQueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("variant_index", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
