# Generated by Django 5.2.16 on 2026-09-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_reminderqueueitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="reminder_campaign_sends_done",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="How many sends of the current bounded push have gone out so far.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="reminder_campaign_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current bounded reminder push (N sends/day for N days) began. Cleared once the push finishes its full run — set again to start a new bounded push.",
                null=True,
            ),
        ),
    ]
