# Generated by Django 5.2.16 on 2026-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_sitesettings_reminder_campaign_sends_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="reminder_sent_today",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="How many reminder-campaign emails have gone out today, counted against REMINDER_DAILY_CAP so the campaign never eats the whole Brevo daily quota and starves transactional email (signup confirmations, receipts, password resets).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="reminder_today_date",
            field=models.DateField(
                blank=True,
                help_text="The date reminder_sent_today's count applies to — reset to 0 automatically once the date rolls over.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="reminder_campaign_sends_done",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Running total of emails sent by the current bounded push, across all days/batches.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="reminder_campaign_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current bounded reminder push (runs for REMINDER_BURST_DAYS days) began. Set again (or pass force=True) to start a new bounded push.",
                null=True,
            ),
        ),
    ]
