# Generated by Django 5.2.16 on 2026-09-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_sitesettings_reminder_sent_today_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="reminder_campaign_paused",
            field=models.BooleanField(
                default=False,
                help_text="Emergency stop: while checked, send_deadline_reminder_if_due does nothing at all (no queueing, no sending) so the full Brevo daily quota is free for transactional email (signup confirmations, receipts, password resets). Queue/progress is left untouched, so unchecking resumes exactly where the campaign left off.",
            ),
        ),
    ]
