# Generated by Django 5.2.16 on 2026-08-16 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0002_rename_paystack_subaccount_code_tutor_paystack_recipient_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("self_paced", "Self-paced (recorded modules)"),
                    ("live", "Virtual (live scheduled sessions)"),
                ],
                default="self_paced",
                help_text="Self-paced: students watch recorded modules anytime. Virtual: students attend scheduled live sessions (Google Meet, Zoom, etc.) at set times.",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "meeting_link",
                    models.URLField(
                        help_text="Google Meet, Zoom, or other video-call link for this session."
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
    ]
