# Generated by Django 5.2.16 on 2026-08-10 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="A short emoji shown on the subject card, e.g. 🌐",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "editor_language",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("js", "JavaScript"),
                            ("python", "Python"),
                            ("php", "PHP"),
                            ("sql", "SQL"),
                            ("java", "Java"),
                            ("csharp", "C#"),
                            ("none", "No live editor"),
                        ],
                        default="none",
                        help_text="html/css/js get a live editable preview. Everything else gets a read-only example + a pre-written expected output.",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=300)),
                (
                    "body",
                    models.TextField(
                        help_text="Article content — basic HTML allowed (headings, paragraphs, lists)."
                    ),
                ),
                (
                    "example_code",
                    models.TextField(
                        blank=True,
                        help_text="For html/css/js subjects: a full HTML document (the editor seeds this and renders it live). For other subjects: a read-only example snippet.",
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(
                        blank=True,
                        help_text="Only shown for subjects without a live preview — the example's expected output.",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="tutorials.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject", "slug"),
                        name="unique_article_slug_per_subject",
                    )
                ],
            },
        ),
    ]
