# Generated by Django 5.2.16 on 2026-08-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0011_seed_csharp_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="editor_language",
            field=models.CharField(
                choices=[
                    ("html", "HTML"),
                    ("css", "CSS"),
                    ("js", "JavaScript"),
                    ("python", "Python"),
                    ("php", "PHP"),
                    ("sql", "SQL"),
                    ("java", "Java"),
                    ("c", "C"),
                    ("cpp", "C++"),
                    ("csharp", "C#"),
                    ("dart", "Dart"),
                    ("flutter", "Flutter"),
                    ("django", "Django"),
                    ("none", "No live editor"),
                ],
                default="none",
                help_text="html/css/js get a live editable preview. Everything else gets a read-only example + a pre-written expected output.",
                max_length=10,
            ),
        ),
    ]
